const groups={all:'All screens',global:'Device & Home',single:'Brain Check',light:'Light Session',trend:'Trends',mine:'Profile'};
const S=[
['H01','global','Today','Daily brain dashboard'],['H02','global','Device unavailable','Resolve a blocking device issue'],
['D01','global','Connect Brainlume','Find and connect the real device'],['D02','global','Fit & signal check','Automatic contact and signal check'],['D03','global','Adjust fit','One clear correction at a time'],
['S01','single','Brain Check','Three-minute check introduction'],['S02','single','Brain Check','EEG collection in progress'],['S03','single','Check paused','Temporary signal interruption'],['S04','single','Building result','Quality and scoring pipeline'],['S05','single','Check Result','Current state and next action'],['S06','single','Six dimensions','Detailed state dimensions'],['S07','single','Not enough data','No unreliable conclusion'],['S08','single','Technical evidence','Quality, channels and algorithm'],
['L01','light','Light Session','Safety confirmation and stages'],['L02','light','Before EEG','Pre-session baseline'],['L03','light','Light Session','Near-infrared session in progress'],['L04','light','Session paused','Light and audio paused together'],['L05','light','End safely?','Stop light and save partial record'],['L06','light','After EEG','Post-session measurement'],['L07','light','After check failed','Retake After only'],['L08','light','Session Result','Before and after change'],['L09','light','Change details','Comparable metric detail'],['L10','light','Session incomplete','Completed stages and interruption'],['L11','light','Limited comparison','Direction only, no false precision'],
['T01','trend','Trends','Weekly overview and history'],['T02','trend','Check record','Historical single result'],['T03','trend','Session record','Historical intervention result'],['T04','trend','Weekly trend','Simple trend and state mix'],['T05','trend','Build your baseline','Low-data empty state'],
['M01','mine','Profile','Device, permissions and help'],['M02','mine','Your Brainlume','Connected device details'],['M03','mine','Permissions','Permission status and control'],['M04','mine','Help & support','Task-based guidance']
].map(([id,g,name,desc])=>({id,g,name,desc}));

const icons={home:'⌂',trend:'⌁',mine:'○',device:'◫',signal:'〰',check:'✓',warn:'!',light:'☼',lock:'▣',help:'?',battery:'▰',chart:'⌁'};
const status=()=>`<div class="status"><b>9:41</b><span>▮▮▮ ⌁ <b class="battery">100</b></span></div>`;
const topBar=s=>`<div class="topbar"><button class="back" aria-label="Go back">‹</button><b>${s.name.toUpperCase()}</b><button class="info" aria-label="Page information">ⓘ</button></div>`;
const nav=on=>`<nav class="bottom-nav">${[['home','Home','H01'],['trend','Trends','T01'],['mine','Profile','M01']].map(([k,t,r])=>`<button data-route="${r}" class="${on===k?'on':''}"><i>${icons[k]}</i>${t}</button>`).join('')}</nav>`;
const button=(t,type='')=>`<button class="button ${type}" data-label="${t}">${t}</button>`;
const row=(ico,title,sub,value='',tone='',route='')=>`<div class="row ${route?'interactive-row':''}" ${route?`data-route="${route}"`:''}><i>${icons[ico]||ico}</i><span><b>${title}</b><small>${sub}</small></span>${value?`<em class="${tone}">${value}</em>`:''}</div>`;
const card=(title,html,cls='')=>`<section class="card ${cls}"><h3>${title}</h3>${html}</section>`;
const product=(label='BRAINLUME DEVICE')=>`<section class="product-card"><div class="product-copy"><b>${label}</b><span>REAL PRODUCT · CONNECTED</span></div><img src="./assets/brainlume-product-real.jpg" alt="Brainlume real product"></section>`;
const stage=n=>`<div class="stage">${['BEFORE','LIGHT','AFTER','RESULT'].map((x,i)=>`<span class="${i<n?'done':''} ${i===n?'active':''}">${i+1}<small>${x}</small></span>`).join('')}</div>`;
const ring=(value,label,tone='cyan',note='')=>`<div class="ring ${tone}" style="--p:${parseFloat(value)||72}"><div><strong>${value}</strong><b>${label}</b>${note?`<small>${note}</small>`:''}</div><span class="ring-sweep"></span></div>`;
const miniRings=()=>`<div class="mini-rings">${[['82%','BRAIN','cyan'],['68%','RECOVERY','green'],['5.4','LIGHT','amber']].map(x=>`<div>${ring(x[0],x[1],x[2])}</div>`).join('')}</div>`;
const bars=(items)=>`<div class="metric-list">${items.map(([n,v,s,t=''])=>`<div><span><b>${n}</b><small>${s}</small></span><em class="${t}">${v}</em><i style="--w:${parseInt(v)||66}%"></i></div>`).join('')}</div>`;
const eegPanel=(mode='live')=>`<section class="eeg-panel ${mode}" data-eeg-mode="${mode}"><header><span><i></i> 3-CHANNEL EEG</span><b>${mode==='degraded'?'RECONNECTING':'LIVE'}</b></header>${[['FP1','LEFT','42'],['FPZ','CENTER','36'],['FP2','RIGHT','45']].map((c,i)=>`<div class="eeg-channel"><label><b>CH${i+1} · ${c[0]}</b><small>${c[1]} · ±${c[2]} μV</small></label><svg viewBox="0 0 280 54" preserveAspectRatio="none"><path class="eeg-grid" d="M0 27H280M70 0V54M140 0V54M210 0V54"/><path class="eeg-path channel-${i+1}" data-channel="${i}" d="M0 27H280"/></svg><span class="quality ${i===1?'q2':''}">${mode==='degraded'?(i===0?'18':'—'):(i===1?'94':'97')}%</span></div>`).join('')}<footer><span>SIMULATED SIGNAL</span><span>256 Hz</span><span>50 μV</span></footer></section>`;
const wave=(mode='live')=>eegPanel(mode);
const chart=()=>`<div class="chart"><svg viewBox="0 0 320 170"><path class="grid" d="M10 25H310M10 75H310M10 125H310M10 165H310"/><path class="area" d="M12 140 58 116 104 122 150 89 196 98 242 61 306 38V165H12Z"/><path d="M12 140 58 116 104 122 150 89 196 98 242 61 306 38"/><g>${[[12,140],[58,116],[104,122],[150,89],[196,98],[242,61],[306,38]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="4"/>`).join('')}</g></svg><div class="days"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span></div></div>`;
const actions=(a,b,type='')=>`<div class="actions">${b?button(b,type==='second-danger'?'danger':'secondary'):''}${button(a,type==='second-danger'?'secondary':type)}</div>`;
const deviceRows=()=>`${row('device','Device connection','Stable connection','GOOD','green')}${row('signal','Contact quality','All key contacts stable','96%','green')}${row('battery','Battery','Enough for this task','86%')}`;
const taskTimer=(time,label,tone='cyan',state='SIGNAL QUALITY')=>`${ring(time,label,tone,state)}${wave('live')}`;
const brainCompare=(compact=false)=>`<div class="brain-compare ${compact?'compact':''}"><div class="brain-state before"><small>BEFORE</small><b>68</b><div class="brain-orb"><img src="./assets/brain-map-before-v1.png" alt="Before brain energy map"><i></i></div><span>BASELINE</span></div><div class="change-arrow"><span>CHANGE</span><i>→</i></div><div class="brain-state after"><small>AFTER</small><b>82</b><div class="brain-orb"><img src="./assets/brain-map-after-v1.png" alt="After brain energy map"><i></i></div><span>POST-SESSION</span></div></div>`;

function body(s){switch(s.id){
case'H01':return `<div class="datebar"><span>‹</span><b>TODAY</b><span>›</span></div>${miniRings()}${card('SIGNAL MONITOR',`<div class="split"><span><b>GOOD</b><small>EEG QUALITY</small></span><span><b class="green">READY</b><small>LIGHT SESSION</small></span></div>`)}<h2>My Day</h2>${row('check','Brain Check','3-minute current state check','03:00','','S01')}${row('light','Light Session','Before · Light · After','27 MIN','','L01')}${nav('home')}`;
case'H02':return `${product()}<h1>DEVICE UNAVAILABLE</h1><p class="lead">Reconnect your Brainlume before starting a check or light session.</p>${card('PRIORITY ACTION',row('device','Connection lost','Last seen 2 minutes ago','OFFLINE','coral'))}${actions('Reconnect','View help')}${nav('home')}`;
case'D01':return `${product('CONNECT BRAINLUME')}<h1>READY TO PAIR</h1><p class="lead">Keep the device powered on and close to this phone.</p>${row('device','Brainlume','Nearby · battery 86%','SELECTED','green')}${row('signal','Other devices','No other device found','REFRESH')}${actions('Connect device')}`;
case'D02':return `${product('FIT & SIGNAL CHECK')}${stage(0)}${deviceRows()}<div class="notice good">Signal has remained stable for 8 seconds.</div>${actions('Start task')}`;
case'D03':return `${product('ADJUST LEFT CONTACT')}<h1>PRESS THE LEFT FOREHEAD MODULE</h1><p class="lead">Move hair away from the contact, then apply light pressure.</p>${row('device','Connection','Stable','PASS','green')}${row('signal','Left contact','Automatic recheck in progress','ADJUST','amber')}${actions('I adjusted it')}`;
case'S01':return `<span class="eyebrow">3 MINUTE CHECK</span><h1>KNOW YOUR CURRENT BRAIN STATE</h1><p class="lead">Stay seated, remain quiet and breathe naturally.</p>${card('WHAT YOU GET','<ul><li>One clear current-state label</li><li>Six state dimensions</li><li>Simple next-step guidance</li></ul>')}${card('BEFORE YOU START','<p>Remove obvious distractions and avoid talking during collection.</p>')}${actions('Start fit check')}`;
case'S02':return `${taskTimer('02:18','REMAINING','cyan','SIGNAL GOOD')}<p class="center">Stay still and breathe normally</p><div class="progress"><i style="width:28%"></i></div>${row('signal','Valid data','Collected 00:42 of 03:00','LIVE','green')}${actions('Pause','Exit check')}`;
case'S03':return `${ring('02:18','PAUSED','coral','RECONNECTING')}${wave('degraded')}<div class="notice warn"><b>Signal temporarily interrupted</b><br>Valid data is saved. Timing resumes automatically after reconnection.</div>${row('device','Bluetooth','Attempting reconnection','WAIT')}${actions('Reconnect','Exit check','')}`;
case'S04':return `<div class="loader"></div><h1 class="center">BUILDING YOUR RESULT</h1><p class="lead center">Quality check · six dimensions · state label · action guidance</p>${card('PROCESSING','<div class="process"><i></i><i></i><i></i><i></i></div><p>A complete template is used if AI wording is unavailable.</p>')}`;
case'S05':return `${ring('82%','BRAIN STATE','green','BALANCED & ALERT')}${card('TODAY\'S SIGNAL','<p>Your alertness is good and stable. Tension load is slightly elevated.</p>')}${bars([['Focus','76','HIGH','cyan'],['Tension load','63','SLIGHTLY HIGH','amber']])}${actions('Start Light Session','View all dimensions')}`;
case'S06':return `<span class="eyebrow">CHECK RESULT</span><h1>SIX DIMENSIONS</h1>${bars([['Focus','76','HIGH','cyan'],['Relaxation','58','MODERATE','green'],['Alertness','72','GOOD','cyan'],['Fatigue load','39','LOW','green'],['Tension load','63','ELEVATED','amber'],['Stability','81','STABLE','green']])}<div class="notice">Higher fatigue and tension values mean higher load—not a better score.</div>${button('View technical evidence','secondary')}`;
case'S07':return `${ring('—','NO RESULT','amber','DATA INSUFFICIENT')}${card('WHY','<p>Left contact was unstable and movement artifacts reduced valid recording time.</p>')}${card('WHAT TO DO','<p>Adjust the left forehead module, then remain seated and still.</p>')}${actions('Check fit and retry','Return home')}`;
case'S08':return `<span class="eyebrow">TECHNICAL LAYER</span><h1>EVIDENCE & QUALITY</h1>${wave('inspect')}${row('check','Overall quality','92% valid data','PASS','green')}${row('chart','Band features','Alpha · Beta · Theta · Delta','EXPAND')}${row('lock','Algorithm version','BL-State 1.0.3','LOGGED')}${card('BOUNDARY','<p>This result describes an observable state for this session. It is not a medical diagnosis.</p>')}`;
case'L01':return `${stage(0)}<span class="eyebrow coral">NEAR-INFRARED SESSION</span><h1>COMPLETE LIGHT EXPERIENCE</h1><p class="lead">About 27 minutes from baseline to final comparison.</p>${card('SESSION FLOW','<ol><li>Before EEG · 3 min</li><li>Near-infrared light + audio · 20 min</li><li>After EEG · 3 min</li><li>Change result</li></ol>')}<div class="notice warn">Do not begin if you feel unwell, are sensitive to light, or have an unhealed head injury.</div>${actions('Confirm safety & begin')}`;
case'L02':return `${stage(0)}${taskTimer('02:35','BEFORE EEG','cyan','BUILDING BASELINE')}<div class="progress"><i style="width:14%"></i></div><p class="center muted">The light session begins automatically when baseline quality passes.</p>${actions('Pause','Exit')}`;
case'L03':return `${stage(1)}${ring('18:36','REMAINING','coral','CONNECTED · 78%')}${row('light','Light output','Near-infrared output stable','STABLE','green')}${row('check','Fit quality','Contacts remain stable','GOOD','green')}${row('signal','Session mode','Recovery preset','ACTIVE','coral')}${actions('Pause','End safely','second-danger')}`;
case'L04':return `${ring('08:14','COMPLETED','amber','SESSION PAUSED')}<h1 class="center">LIGHT AND AUDIO PAUSED</h1>${card('BEFORE YOU CONTINUE','<p>Keep the device fitted and continue only if you feel comfortable.</p>')}${actions('Continue session','End safely','second-danger')}`;
case'L05':return `${ring('■','LIGHT OFF','coral','SAFETY CONFIRMATION')}<h1 class="center">END THIS SESSION SAFELY?</h1><div class="notice warn">Light stops immediately. This record will be saved as incomplete and will not produce a full Before / After conclusion.</div>${actions('End now','Continue session','danger')}`;
case'L06':return `${stage(2)}${taskTimer('02:41','AFTER EEG','cyan','SAME POSTURE & SETTING')}<div class="progress"><i style="width:11%"></i></div><p class="center muted">If this check fails, only After EEG needs to be repeated.</p>${actions('Pause','Exit')}`;
case'L07':return `${ring('58%','VALID DATA','amber','AFTER CHECK FAILED')}${card('ISSUE','<p>Movement artifacts were too high. The completed light session remains saved.</p>')}${card('RECOMMENDATION','<p>Adjust the forehead contact and repeat After EEG only.</p>')}${actions('Retry After EEG','Save incomplete record')}`;
case'L08':return `<div class="recovery-heading"><span>RECOVERY</span><strong>+14</strong><small>MORE STABLE OVERALL</small></div>${brainCompare()}${card('MAIN CHANGE','<p>Tension load decreased, relaxation increased and alertness remained stable.</p>')}${actions('Return home','View details')}`;
case'L09':return `<span class="eyebrow">BEFORE / AFTER</span><h1>CHANGE DETAILS</h1>${bars([['Relaxation','62','46 → 62','green'],['Tension load','54','71 → 54','green'],['Stability','72','59 → 72','green'],['Alertness','68','70 → 68','cyan']])}${card('HOW TO READ THIS','<p>This session appears more stable, but a single change does not represent treatment efficacy.</p>')}${card('NEXT STEP','<p>Begin with a structured task and collect more sessions before judging a trend.</p>')}`;
case'L10':return `${ring('08:14','LIGHT COMPLETED','amber','SESSION INCOMPLETE')}${card('STAGE RECORD',`${row('check','Before EEG','Quality passed','DONE','green')}${row('light','Light session','08:14 of 20:00','PARTIAL','amber')}${row('signal','After EEG','Not started','—')}`)}${card('INTERRUPTION','<p>User selected End Safely. No full comparison was generated.</p>')}${actions('Return home','View record')}`;
case'L11':return `${ring('↕','DIRECTION ONLY','amber','LIMITED COMPARISON')}${card('OBSERVABLE DIRECTION','<p>Relaxation increased and tension load decreased. Exact percentages are hidden because After quality was lower.</p>')}${bars([['Relaxation','62','UPWARD','green'],['Tension load','54','DOWNWARD','green'],['Stability','72','MORE STABLE','cyan']])}<div class="notice warn">Repeat under similar conditions before making a personal conclusion.</div>`;
case'T01':return `<div class="seg"><span class="on">ALL</span><span>CHECKS</span><span>SESSIONS</span></div>${miniRings()}${card('THIS WEEK','<p>4 valid checks · 2 light sessions</p>'+chart())}${row('check','Today · 09:41','Brain Check · Balanced & alert','82','','T02')}${row('light','Yesterday · 21:30','Light Session · More stable','+14','','T03')}${nav('trend')}`;
case'T02':return `<span class="eyebrow">AUG 12 · 09:41</span>${ring('82%','BRAIN STATE','green','QUALITY PASSED')}${bars([['Focus','76','HIGH','cyan'],['Stability','81','STABLE','green'],['Tension load','63','ELEVATED','amber']])}${card('GUIDANCE AT THE TIME','<p>Best suited to a structured task after a brief relaxation break.</p>')}`;
case'T03':return `<span class="eyebrow">AUG 11 · 21:30</span><div class="recovery-heading compact"><span>RECOVERY</span><strong>+14</strong><small>COMPLETE RECORD</small></div>${brainCompare(true)}${bars([['Relaxation','62','UP','green'],['Tension load','54','DOWN','green'],['Stability','72','UP','cyan']])}`;
case'T04':return `<div class="seg"><span class="on">FOCUS</span><span>RELAX</span><span>FATIGUE</span></div><h1>WEEKLY TREND</h1>${chart()}${card('STATE MIX','<p>Balanced & alert 2 · Focused 1 · Mild fatigue 1</p>')}<div class="notice">Based on 4 valid checks. Small datasets do not create a “brain health profile”.</div>`;
case'T05':return `${ring('0','VALID CHECKS','amber','BUILD YOUR BASELINE')}<h1 class="center">NOT ENOUGH DATA YET</h1><p class="lead center">Complete at least three valid checks before viewing a basic trend.</p>${button('Start your first check')}${nav('trend')}`;
case'M01':return `${product('YOUR BRAINLUME')}${row('device','Your device','Connected · battery 86%','›','','M02')}${row('lock','Permissions','Bluetooth · notifications · health data','›','','M03')}${row('help','Help & support','Fit · check · light session','›','','M04')}${row('chart','Account & data','Sync and deletion controls','›')}${row('check','About Brainlume','App version 1.0.0','›')}${nav('mine')}`;
case'M02':return `${product()}<div class="device-status"><span>● DEVICE CONNECTED</span><b>86% ▰</b></div>${row('signal','Signal self-test','Last check today at 09:41','START')}${row('battery','Battery & charging','About 3 hours remaining','VIEW')}${row('device','Firmware','Version 1.0.3 · up to date','CHECK')}${row('help','Fit guidance','Open visual guide','›')}${button('Disconnect device','danger')}`;
case'M03':return `<span class="eyebrow">DATA CONTROL</span><h1>PERMISSIONS</h1><p class="lead">Permissions are used only for device connection, task status and record management.</p>${row('device','Bluetooth','Connect to Brainlume','ALLOWED','green')}${row('check','Notifications','Completion and issue alerts','ALLOWED','green')}${row('chart','Health data','Optional context records','NOT ALLOWED')}${row('lock','Analytics consent','Improve algorithm quality','NOT JOINED')}<div class="notice">Revoking access may affect connection or task recovery. The app explains the impact first.</div>`;
case'M04':return `<span class="eyebrow">SUPPORT</span><h1>HOW CAN WE HELP?</h1>${row('device','Fit the device correctly','Forehead contact and comfort','›')}${row('signal','Improve signal quality','Movement, contact and environment','›')}${row('light','Light session safety','Pause and End Safely','›')}${row('battery','Connection & battery','Reconnect, charge and recover','›')}${row('chart','Understand results','Dimensions, trends and limits','›')}${card('STILL NEED HELP?','<p>Share device status and task stage. Raw EEG is not attached by default.</p>'+button('Contact support','secondary'))}`;
}}

function phone(s){const mainNav=s.g==='trend'?'trend':s.g==='mine'?'mine':null;return `<section class="phone screen-${s.id.toLowerCase()} ${mainNav?'with-nav':''}">${status()}${topBar(s)}<main>${body(s)}</main><div class="toast" role="status"></div></section>`}

let activeInterval=null, activeTimeout=null, eegFrame=null;
const actionRoutes={
H02:{Reconnect:'D01','View help':'M04'},D01:{'Connect device':'D02'},D02:{'Start task':'FLOW'},D03:{'I adjusted it':'D02'},
S01:{'Start fit check':'D02'},S02:{Pause:'S03','Exit check':'H01'},S03:{Reconnect:'S02','Exit check':'H01'},
S05:{'Start Light Session':'L03','View all dimensions':'S06'},S06:{'View technical evidence':'S08'},S07:{'Check fit and retry':'D03','Return home':'H01'},
L01:{'Confirm safety & begin':'D02'},L02:{Pause:'S03',Exit:'H01'},L03:{Pause:'L04','End safely':'L05'},L04:{'Continue session':'L03','End safely':'L05'},L05:{'End now':'L10','Continue session':'L03'},L06:{Pause:'S03',Exit:'L10'},L07:{'Retry After EEG':'L06','Save incomplete record':'L10'},L08:{'Return home':'H01','View details':'L09'},L10:{'Return home':'H01','View record':'T03'},
T05:{'Start your first check':'S01'},M02:{'Disconnect device':'H02'}
};
const timerConfig={S02:[138,28,'S04'],L02:[155,31,'L03'],L03:[1116,224,'L06'],L06:[161,33,'L08']};

function cleanup(){clearInterval(activeInterval);clearTimeout(activeTimeout);if(eegFrame)cancelAnimationFrame(eegFrame);activeInterval=activeTimeout=eegFrame=null}
function commitRoute(id,replace=false){const u=new URL(location.href);u.search='';u.searchParams.set('screen',id);replace?history.replaceState({id},'',u):history.pushState({id},'',u);render()}
function route(id,replace=false){cleanup();const phone=document.querySelector('.phone');const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!phone||reduceMotion)return commitRoute(id,replace);phone.classList.add('is-leaving');activeTimeout=setTimeout(()=>commitRoute(id,replace),180)}
function showToast(text){const t=document.querySelector('.toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function animateRings(){requestAnimationFrame(()=>document.querySelectorAll('.ring').forEach((r,i)=>setTimeout(()=>r.classList.add('ready'),i*90)))}
function animateEEG(){const panel=document.querySelector('.eeg-panel');if(!panel)return;const paths=[...panel.querySelectorAll('.eeg-path')];const degraded=panel.dataset.eegMode==='degraded';const start=performance.now();function frame(now){const t=(now-start)/1000;paths.forEach((p,ch)=>{const pts=[];for(let x=0;x<=280;x+=2){const phase=x*.085+t*(2.4+ch*.42);const alpha=Math.sin(phase*(1.1+ch*.09))*((ch===1?7:10));const beta=Math.sin(phase*3.25+t*1.7)*(ch===2?5.6:3.8);const theta=Math.sin(phase*.44-t*.7)*3.5;const artifact=Math.sin(x*.73+t*7.2)*1.1;let y=27+alpha+beta+theta+artifact;if(degraded){y=27+(y-27)*.18;if(x>92&&x<176)y=27;}pts.push(`${x},${Math.max(3,Math.min(51,y)).toFixed(1)}`)}p.setAttribute('d','M'+pts.join(' L'))});eegFrame=requestAnimationFrame(frame)}eegFrame=requestAnimationFrame(frame)}
function runTimer(id){const c=timerConfig[id];if(!c)return;let remaining=c[0];const el=document.querySelector('.ring strong');const bar=document.querySelector('.progress i');activeInterval=setInterval(()=>{remaining=Math.max(0,remaining-c[1]);if(el)el.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(bar)bar.style.width=`${Math.min(100,(1-remaining/c[0])*100)}%`;if(!remaining){clearInterval(activeInterval);showToast('Stage complete');activeTimeout=setTimeout(()=>route(c[2]),650)}},1000)}
function afterRender(s){animateRings();animateEEG();runTimer(s.id);if(s.id==='S04')activeTimeout=setTimeout(()=>route('S05'),1100);document.querySelector('.back')?.addEventListener('click',()=>history.length>1?history.back():route('H01',true));document.querySelector('.info')?.addEventListener('click',()=>showToast(`${s.id} · ${s.desc}`));document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>{navigator.vibrate?.(8);route(el.dataset.route)}));document.querySelectorAll('.seg span').forEach(el=>el.addEventListener('click',()=>{el.parentElement.querySelectorAll('span').forEach(x=>x.classList.remove('on'));el.classList.add('on');showToast(`${el.textContent.trim()} view selected`)}));if(s.id==='M03')document.querySelectorAll('.row').forEach(el=>el.addEventListener('click',()=>{const v=el.querySelector('em');if(!v)return;const enabled=v.textContent==='ALLOWED';v.textContent=enabled?'NOT ALLOWED':'ALLOWED';v.classList.toggle('green',!enabled);showToast(enabled?'Permission disabled':'Permission enabled')}));document.querySelectorAll('.button').forEach(btn=>btn.addEventListener('click',()=>{navigator.vibrate?.(10);const label=btn.dataset.label;let target=actionRoutes[s.id]?.[label];if(s.id==='S01')sessionStorage.setItem('brainlumeFlow','single');if(s.id==='L01')sessionStorage.setItem('brainlumeFlow','light');if(target==='FLOW')target=sessionStorage.getItem('brainlumeFlow')==='light'?'L02':'S02';if(s.id==='S05'&&label==='Start Light Session')showToast('Current check reused as Before');if(target)setTimeout(()=>route(target),s.id==='S05'&&label==='Start Light Session'?700:0)}))}
function render(){cleanup();const q=new URLSearchParams(location.search);if(q.get('gallery')==='1'){const g=q.get('group')||'all';document.body.className='';document.querySelector('#app').innerHTML=`<div class="gallery"><header><div><h1><b>Brainlume</b> · Interactive Prototype</h1><p>33 connected screens · mobile simulation</p></div><nav>${Object.entries(groups).map(([k,v])=>`<a class="${g===k?'on':''}" href="?gallery=1&group=${k}">${v}</a>`).join('')}</nav></header><div class="grid">${S.filter(s=>g==='all'||s.g===g).map(s=>`<article><a href="?screen=${s.id}">${phone(s)}</a><b>${s.id} · ${s.name}</b><small>${s.desc}</small></article>`).join('')}</div></div>`;return}const id=q.get('screen')||'H01';const s=S.find(x=>x.id===id)||S[0];document.body.className='prototype';document.querySelector('#app').innerHTML=phone(s);afterRender(s)}
window.addEventListener('popstate',render);render();
